FIX: use boost compatibility macro
Compilation fails for me (gcc-4.6.2):
src/UFTTCore.cpp: In member function ‘void UFTTCore::initialize()’:
src/UFTTCore.cpp:353:89: error: no matching function for call to ‘move(boost::thread)’
src/UFTTCore.cpp:353:89: note: candidates are:
/usr/include/boost/move/move.hpp:324:97: note: template<class T> typename boost::move_detail::disable_if<boost::has_move_emulation_enabled_aux<T>, T&>::type boost::move(T&)
/usr/include/boost/move/move.hpp:330:96: note: template<class T> typename boost::move_detail::enable_if<boost::has_move_emulation_enabled<T>, boost::rv<T>&>::type boost::move(T&)
/usr/include/boost/move/move.hpp:336:96: note: template<class T> typename boost::move_detail::enable_if<boost::has_move_emulation_enabled<T>, boost::rv<T>&>::type boost::move(boost::rv<T>&)
/usr/include/boost/move/move.hpp:943:6: note: template<class I, class O> O boost::move(I, I, O)
/usr/include/boost/thread/detail/move.hpp:55:124: note: typename boost::enable_if<boost::is_convertible<T&, boost::detail::thread_move_t<T> >, boost::detail::thread_move_t<T> >::type boost::move(T&) [with T = boost::thread, typename boost::enable_if<boost::is_convertible<T&, boost::detail::thread_move_t<T> >, boost::detail::thread_move_t<T> >::type = boost::detail::thread_move_t<boost::thread>]
/usr/include/boost/thread/detail/move.hpp:55:124: note:   no known conversion for argument 1 from ‘boost::thread’ to ‘boost::thread&’
/usr/include/boost/thread/detail/move.hpp:62:37: note: template<class T> boost::detail::thread_move_t<T> boost::move(boost::detail::thread_move_t<T>)
make[2]: *** [src/CMakeFiles/uftt-core.dir/UFTTCore.o] Error 1

http://www.boost.org/doc/libs/1_50_0/doc/html/thread/emulations.html says:
Note that ::boost::move can not be used in this case as thread is not implicitly convertible to thread&.
To make the code portable Boost.Thread the user needs to use a macro BOOST_THREAD_MAKE_RV_REF that can be used as in

Now at least it should compile again, but I'm not sure if this is the proper solution.